package com.anchr.core.search.interfaces.rest.dto;

import jakarta.annotation.Nullable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Search answer response.
 */
@Data
@Builder
public class SearchAnswerDTO implements Serializable {

    private String answer;
    private List<CitationDTO> citations;
    private List<SearchResultDTO> results;
    private AnswerTraceDTO answerTrace;

    @Data
    @Builder
    public static class CitationDTO implements Serializable {
        private Integer citationIndex;
        private String segmentId;
        private String assetId;
        private String kbId;
        private String fileName;
        private Integer pageNo;
        private String snippet;
        private CitationWhy why;
    }

    @Data
    @Builder
    public static class AnswerTraceDTO implements Serializable {
        private String mode;
        private boolean grounded;
        private String fallbackReason;
    }

    /**
     * Explains why a particular segment was selected as a citation — the retrieval-level rationale.
     * Deterministically built from retrieval signals, not generated by LLM.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CitationWhy implements Serializable {

        private static final String VECTOR = "VECTOR";
        private static final String CONTENT = "CONTENT";
        private static final String OCR = "OCR";
        private static final String TAG = "TAG";

        @Nullable
        private Double score;

        @Builder.Default
        private List<String> hitSources = new ArrayList<>();

        @Nullable
        private MatchedBy matchedBy;

        @Nullable
        private String matchSummary;

        @Data
        @Builder
        @NoArgsConstructor
        @AllArgsConstructor
        public static class MatchedBy implements Serializable {
            private boolean vector;
            private boolean title;
            private boolean content;
            private boolean ocr;
        }

        public static String buildSummary(@Nullable Double score,
                                          @Nullable List<String> hitSources,
                                          @Nullable MatchedBy matchedBy) {
            List<String> parts = new ArrayList<>();
            boolean hasVector = containsIgnoreCase(hitSources, VECTOR);
            boolean hasContent = containsIgnoreCase(hitSources, CONTENT);
            boolean hasOcr = containsIgnoreCase(hitSources, OCR);
            boolean hasTag = containsIgnoreCase(hitSources, TAG);

            if (hasVector) {
                parts.add("语义匹配");
            }

            List<String> keywordFields = new ArrayList<>();
            if (matchedBy != null) {
                if (matchedBy.content) keywordFields.add("内容");
                if (matchedBy.title) keywordFields.add("标题");
                if (matchedBy.ocr) keywordFields.add("OCR");
            } else {
                if (hasContent) keywordFields.add("内容");
                if (hasOcr) keywordFields.add("OCR");
            }
            if (!keywordFields.isEmpty()) {
                parts.add(String.join("+", keywordFields) + "关键词命中");
            }

            if (hasTag && (matchedBy != null || keywordFields.isEmpty())) {
                parts.add("标签匹配");
            }

            if (hasOcr && matchedBy == null && keywordFields.isEmpty()) {
                parts.add("OCR文本匹配");
            }

            if (parts.isEmpty()) {
                parts.add("无命中信号");
            }

            StringBuilder result = new StringBuilder(String.join(" + ", parts));
            if (score != null) {
                result.append(String.format(Locale.ROOT, " (score: %.2f)", score));
            }
            return result.toString();
        }

        private static boolean containsIgnoreCase(@Nullable List<String> sources, String value) {
            if (sources == null || sources.isEmpty()) {
                return false;
            }
            return sources.stream().anyMatch(value::equalsIgnoreCase);
        }
    }
}
