create table if not exists knowledge_base (
  id bigint primary key,
  name varchar(128) not null,
  description text,
  status varchar(32) not null,
  document_count int not null default 0,
  segment_count int not null default 0,
  last_ingested_at timestamp null,
  created_by varchar(64) not null default 'system',
  updated_by varchar(64) not null default 'system',
  created_at timestamp not null,
  updated_at timestamp not null,
  deleted_at timestamp null,
  index idx_kb_updated_at (updated_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists asset (
  id bigint primary key,
  kb_id bigint not null,
  file_name varchar(512) not null,
  title varchar(512),
  file_type varchar(32) not null,
  mime_type varchar(128),
  size_bytes bigint,
  file_hash varchar(128),
  version_group_id varchar(64) null,
  version_no int not null default 1,
  previous_asset_id varchar(64) null,
  object_key varchar(1024),
  preview_object_key varchar(1024),
  thumbnail_key varchar(1024),
  source_url text,
  parse_status varchar(32) not null,
  index_status varchar(32) not null,
  segment_count int not null default 0,
  indexed_segment_count int not null default 0,
  embedding_profile varchar(128),
  error_code varchar(128),
  error_message text,
  created_by varchar(64) not null default 'system',
  updated_by varchar(64) not null default 'system',
  created_at timestamp not null,
  updated_at timestamp not null,
  deleted_at timestamp null,
  index idx_doc_kb_status (kb_id, parse_status, index_status),
  index idx_doc_hash (kb_id, file_hash),
  index idx_doc_created_at (kb_id, created_at),
  index idx_doc_version_group (kb_id, version_group_id, version_no)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists ingestion_task (
  id bigint primary key,
  kb_id bigint not null,
  source_type varchar(32) not null,
  client_request_id varchar(128) character set utf8mb4 collate utf8mb4_bin null,
  request_hash varchar(80) character set ascii collate ascii_bin null,
  dedupe_strategy varchar(32) character set ascii collate ascii_bin null,
  status varchar(32) not null,
  total_count int not null default 0,
  success_count int not null default 0,
  failure_count int not null default 0,
  running_count int not null default 0,
  created_by varchar(64) not null default 'system',
  updated_by varchar(64) not null default 'system',
  created_at timestamp not null,
  updated_at timestamp not null,
  finished_at timestamp null,
  unique key uk_ingestion_task_creator_request (created_by, client_request_id),
  index idx_task_kb_created (kb_id, created_at),
  index idx_task_status (status)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;


create table if not exists ingestion_task_item (
  id bigint primary key,
  task_id bigint not null,
  current_execution_id bigint null,
  kb_id bigint not null,
  asset_id varchar(64),
  file_name varchar(512),
  file_hash varchar(128),
  source_url text,
  parse_attempt int not null default 1,
  docling_request_id varchar(200) character set utf8mb4 collate utf8mb4_bin null,
  docling_job_id varchar(64) character set ascii collate ascii_bin null,
  source_revision varchar(80) character set ascii collate ascii_bin null,
  execution_stage varchar(32) character set ascii collate ascii_bin
    not null default 'PARSE_SUBMIT',
  execution_epoch bigint not null default 1,
  stage_attempt int not null default 0,
  stage_retry_count int not null default 0,
  stage_started_at datetime(6) null,
  next_action_at datetime(6) null,
  lease_token varchar(64) character set ascii collate ascii_bin null,
  lease_until datetime(6) null,
  parse_request_snapshot json null,
  parse_result_object_key varchar(1024) character set utf8mb4 collate utf8mb4_bin null,
  stage varchar(32) not null,
  status varchar(32) not null,
  progress int not null default 0,
  dedupe_strategy varchar(32) null,
  dedupe_result varchar(32),
  duplicate_asset_id varchar(64) null,
  error_code varchar(128),
  error_message text,
  created_at timestamp not null,
  updated_at timestamp not null,
  finished_at timestamp null,
  index idx_ingestion_item_current_execution (current_execution_id, id),
  index idx_ingestion_item_claim (status, next_action_at, lease_until, id),
  index idx_ingestion_task_claim (task_id, status, next_action_at, lease_until, id),
  index idx_task_item_task (task_id),
  index idx_task_item_asset (asset_id),
  index idx_task_item_kb_status (kb_id, status)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;


create table if not exists activity_event (
  id bigint primary key,
  user_id varchar(32) not null default 'system',
  event_type varchar(64) not null,
  resource_type varchar(64),
  resource_id varchar(128),
  payload json,
  created_at timestamp not null,
  index idx_activity_type_created (event_type, created_at)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci;

create table if not exists capability_config (
    id bigint primary key,
    capability      varchar(32) not null,
    base_url        varchar(512) not null,
    api_key_enc     varchar(512) not null,
    model_name      varchar(128),
    extra_config    json,
    enabled         boolean not null default false,
    updated_by varchar(64) not null default 'system',
    updated_at      timestamp not null,
    deleted_at      timestamp null
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists storage_config (
    id bigint primary key,
    endpoint        varchar(512) not null,
    access_key_enc  varchar(512) not null,
    secret_key_enc  varchar(512) not null,
    bucket          varchar(256) not null,
    region          varchar(64),
    prefix          varchar(256),
    role_arn        varchar(256),
    enabled         boolean not null default true,
    updated_by varchar(64) not null default 'system',
    updated_at      timestamp not null,
    deleted_at      timestamp null
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
